spring.application.name=API
spring.datasource.url=jdbc:postgresql://localhost:5431/DB_VOLLMED
spring.datasource.username=kelwin
spring.datasource.password=123456
#//Mostra o log do Spring enviando as requisições e formata no modelo SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.data.web.pageable.page-parameter=pagina - Alterando a forma de chamar os parametros de paginação
#spring.data.web.pageable.size-parameter=tamanho
#spring.data.web.sort.sort-parameter=ordem
server.error.include-stacktrace=never
api.security.token.secret=${JWT_SECRET:12345678}